=== ish1289/Project/xml-schema/xml-schemas/examples/example23/BookSeller.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.BookRetailers.org"
            xmlns="http://www.BookRetailers.org"
            elementFormDefault="qualified">
    <xsd:element name="BookSeller">
        <xsd:complexType>
             <xsd:sequence>
                 <xsd:element name="Book" maxOccurs="unbounded">
                     <xsd:complexType>
                         <xsd:sequence>
                             <xsd:element name="Title" type="xsd:string"/>
                             <xsd:element name="Author" type="xsd:string"/>
                             <xsd:element name="Date" type="xsd:string"/>
                             <xsd:element name="ISBN" type="xsd:string"/>
                             <xsd:element name="Publisher" type="xsd:string"/>
                             <xsd:any minOccurs="0"/>
                         </xsd:sequence>
                     </xsd:complexType>
                 </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== ish1289/Project/xml-schema/xml-schemas/examples/example23/BookSeller.xml
<?xml version="1.0"?>
<BookSeller xmlns="http://www.BookRetailers.org"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation=
                           "http://www.BookRetailers.org
                            BookSeller.xsd
                            http://www.repository.org
                            SchemaRepository.xsd">
        <Book>
                <Title>My Life and Times</Title>
                <Author>Paul McCartney</Author>
                <Date>1998</Date>
                <ISBN>1-56592-235-2</ISBN>
                <Publisher>McMillin Publishing</Publisher>
                <Reviewer xmlns="http://www.Reviewer.org">
                    <Name>
                        <First>Roger</First>
                        <Last>Costello</Last>
                    </Name>
                </Reviewer>
        </Book>
        <Book>
                <Title>Illusions The Adventures of a Reluctant Messiah</Title>
                <Author>Richard Bach</Author>
                <Date>1977</Date>
                <ISBN>0-440-34319-4</ISBN>
                <Publisher>Dell Publishing Co.</Publisher>
        </Book>
        <Book>
                <Title>The First and Last Freedom</Title>
                <Author>J. Krishnamurti</Author>
                <Date>1954</Date>
                <ISBN>0-06-064831-7</ISBN>
                <Publisher>Harper &amp; Row</Publisher>
        </Book>
</BookSeller>
