=== ish1289/Project/xml-schema/xml-schemas/examples/example33/Y2KFamilyReunion.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.CostelloReunion.org"
            xmlns="http://www.CostelloReunion.org"
            xmlns:reunion="http://www.CostelloReunion.org"
            elementFormDefault="qualified">
    <xsd:element name="Y2KFamilyReunion">
        <xsd:complexType>
             <xsd:sequence>
                 <xsd:element name="Participants">
                     <xsd:complexType>
                         <xsd:sequence>
                             <xsd:element name="Name" minOccurs="0" maxOccurs="unbounded">
                                 <xsd:complexType>
                                     <xsd:sequence>
                                         <xsd:element name="First" type="xsd:string"/>
                                         <xsd:element name="Last" type="xsd:string"/>
                                     </xsd:sequence>
                                  </xsd:complexType>
                             </xsd:element>
                         </xsd:sequence>
                     </xsd:complexType>
                 </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
        <xsd:key name="PK">
            <xsd:selector xpath="reunion:Participants/reunion:Name"/>
            <xsd:field xpath="reunion:First"/>
            <xsd:field xpath="reunion:Last"/>
        </xsd:key>
    </xsd:element>
</xsd:schema>

=== ish1289/Project/xml-schema/xml-schemas/examples/example33/Y2KFamilyReunion.xml
<?xml version="1.0"?>
<Y2KFamilyReunion xmlns="http://www.CostelloReunion.org"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation=
                              "http://www.CostelloReunion.org
                               Y2KFamilyReunion.xsd">
        <Participants>
            <Name><First>Peter</First><Last>Brown</Last></Name>
            <Name><First>Peter</First><Last>Costello</Last></Name>
        </Participants>
</Y2KFamilyReunion>
